### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by tkraan** [dalen/ide-puppet#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 18.04.1
**Thrown From**: [ide-puppet](https://github.com/dalen/ide-puppet) package 1.3.1

### Stack Trace

Uncaught Error: Connection is closed.

```
At /home/tkraan/.atom/packages/ide-puppet/node_modules/vscode-jsonrpc/lib/main.js:613

Error: Connection is closed.
    at /packages/ide-puppet/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-puppet/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-puppet/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-puppet/node_modules/atom-languageclient/build/lib/languageclient.js:242:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-puppet/node_modules/atom-languageclient/build/lib/languageclient.js:131:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-puppet/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:181:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at disposables.add.displayLayer.onDidChange.changes (/usr/share/atom/resources/app/src/text-editor.js:614:26)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at DisplayLayer.emitDeferredChangeEvents (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:819:26)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1800:30)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:996:18)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:2002:30)
    at TextEditor.moveCursors (/usr/share/atom/resources/app/src/text-editor.js:2875:23)
    at TextEditor.setCursorScreenPosition (/usr/share/atom/resources/app/src/text-editor.js:2686:23)
    at TextEditorComponent.didMouseDownOnContent (/usr/share/atom/resources/app/src/text-editor-component.js:1800:25)
```

### Commands

```
     -6:45.9.0 intentions:highlight (input.hidden-input)
     -6:45.4.0 core:copy (input.hidden-input)
     -6:41.1.0 intentions:highlight (input.hidden-input)
     -6:41 core:select-all (input.hidden-input)
     -6:40.7.0 core:paste (input.hidden-input)
     -6:39.1.0 intentions:highlight (input.hidden-input)
     -6:38.8.0 core:undo (input.hidden-input)
     -6:34.4.0 intentions:highlight (input.hidden-input)
     -6:34.2.0 core:paste (input.hidden-input)
     -5:56.2.0 intentions:highlight (input.hidden-input)
     -5:55.8.0 core:copy (input.hidden-input)
     -5:44.6.0 intentions:highlight (input.hidden-input)
     -5:44.4.0 core:paste (input.hidden-input)
  2x -1:01.6.0 editor:newline (input.hidden-input)
  4x -0:48.4.0 core:backspace (input.hidden-input)
     -0:35.2.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy-signal 1.4.3 
ide-puppet 1.3.1 
intentions 1.1.5 
language-puppet 0.23.0 
linter 2.2.0 
linter-puppet-lint-for-linter-3 0.2.2 
linter-puppet-parser 0.1.1 
linter-ui-default 1.7.1 
```

**Comment by IvanBayan** [comment]
I've faced with same issue.
